spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/savushkin
#    username: postgres
#    password: postgres
    username: scada_user
    password: scada123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: channel

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082

jwt:
  secret: f8d7e2c6a1b3f9e5d8c4a7b2e1f3c5d6a8b4e7f2c9d1a3b5e6f8c2d4e7f9a0b1
  expiration-ms: 3600000